[package]
name = "rs-type-clipboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.8.2"
inputbot = { git = "https://github.com/obv-mikhail/InputBot", branch = "develop" }